### ISSUE TITLE
წაიკითხეთ  !!

### ISSUE THREAD

**Issue by kujma10-zz** [kujma10-zz/ShopManagment#37]
პროექტი გადავაკეთე simplemembership ავტორიზაციაზე. ანუ თავიდან რო სტანდარტული ლოგინია იმაზე. ხოდა მაგისთვის საჭირო გახდა ადმინს ცხრილის შეცვლა. სინკის მერე უნდა ქნათ შემდეგი რამეები:
1. ადმინს ცხრლი ბაზაში გადააკეთეთ ისე როგორც ახალ  ქუერიშია(მარტო აიდი და ნეიმი რო აქვს)
2. შექმენით ეგ ცხრილი და დატოვეთ ცარიელი, არაფერი არ ჩააგდოთ.
3. `web.config`-ში ჩაეემატა ახალი სტრინგი, ხოდა მომიწია დაკომიტება. ამიტომ ვებ.კონფიგ-ში გადააკეთეთ ის ძველი სახელი ახლიდან და + ახალ სტრინგშიც თქვენი სახელი ჩაუწერეთ ჩემის მაგივრად
4. განაახლეთ ენთითი მოდელი
5. `[InitializeSimpleMembership]` დაუწერეთ `HomeController`-ის კლასს თავში
6. გაუშვით და ნახეთ თუ მუშაობს ლოგინი (პაროლები 123 ის მაგივრად გახდა **123456**)

თქვენ რაც კონტროლერებზეც მუშაობთ კლასის თავში დაუსვით ასე: [Authorize(Roles = ("StorageOperator ან ShopOperator ან ShopManager"))] იმის მიხედვით თუ რომელ ტიპს უნდა ჰქონდეს მხოლოდ წვდომა

**Comment by kujma10-zz** [comment]
@gkiko @Jilberta

**Comment by Jilberta** [comment]
[Authorize(Roles = ("StorageOperator ან ShopOperator ან ShopManager"))]  aq tu ors aqvs cvdoma ?

**Comment by gkiko** [comment]
მთელი ბაზის წაშლა დამჭირდა იმ ცხრილის განსაახლებლად :rage1: 
sagol @kujma10 :clap:

**Comment by kujma10-zz** [comment]
@Jilberta  [Authorize(Roles = ("StorageOperator, ShopManager"))]
