### ISSUE TITLE
ShopManager: დაემატოს მაღაზიის გამყიდველის ჩამატების ფუნქცია

### ISSUE THREAD

**Issue by kujma10-zz** [kujma10-zz/ShopManagment#39]
ადვილი გასაკეთებელია და ბონუსსაც გამოვტყუებთ, რეგისტრაცია უკვე გამზადებულია და მხოლოდ ლინკის ჩამატების პონტი იქნება.

**Comment by Jilberta** [comment]
ok

**Comment by kujma10-zz** [comment]
კიდე ამის ჩამატება მოგიწევს რეგისტრაციის დროს 
if (!Roles.IsUserInRole("axaligamyidvelissaxeli", "ShopOperator"))
                            Roles.AddUserToRole("axaligamyidvelissaxeli", "ShopOperator");

**Comment by kujma10-zz** [comment]
@Jilberta  ამას მე გავაკეთებ, შენ ისტორიას მიხედე და იმ ბაგს
